configuration: Release

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

nuget:
  account_feed: true
  project_feed: true

# Restore NuGet packages before running MSBuild
before_build:
  - nuget restore

build:
  verbosity: minimal

after_test:
  - ps: Get-ChildItem "($env:APPVEYOR_BUILD_FOLDER)Subterran.Basic\bin\$($env:configuration)" -include *.pdb,*.xml -recurse -force | Remove-Item -force

artifacts:
  - path: Subterran.Basic\bin\$(configuration)
    name: Subterran Libraries
    type: zip

  - path: Examples\TropicalIsland\bin\$(configuration)
    name: TropicalIsland Example
    type: zip