os: Visual Studio 2015 CTP 6
configuration: Release

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

nuget:
  account_feed: true
  project_feed: true

# Restore NuGet packages before running MSBuild
before_build:
  - nuget restore

build:
  verbosity: minimal
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
# If the symbol server dies, disable this so nuget updates can go through
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages

artifacts:
  # Subterran.Toolbox contains all the Subterran libraries in the output
  - path: Subterran.Toolbox\bin\$(configuration)
    name: Subterran Libraries
    type: zip

  - path: Examples\TropicalIsland\bin\$(configuration)
    name: Tropical Island Example
    type: zip

  - path: Examples\VoxelWorld\bin\$(configuration)
    name: Voxel World Example
    type: zip
