configuration: Release

# Restore NuGet packages before running MSBuild
before_build:
  - nuget restore

build:
  verbosity: minimal

artifacts:
  - path: .\*.nupkg

# Deploy the build to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: dkYApyftz6PXyNgyXm+BUvctSdOu2LuuendpqDRCJpi6g5t8xVDXVmaTJRHOdvJX
  skip_symbols: false
  artifact: /.*\.nupkg/
  
