configuration: Release

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

nuget:
  account_feed: true
  project_feed: true

# Restore NuGet packages before running MSBuild
before_build:
  - nuget restore

build:
  verbosity: minimal

artifacts:
  - path: Subterran\bin\$(configuration)\
    name: Subterran Core
    type: zip

  - path: Subterran.Rendering\bin\$(configuration)\
    name: Subterran Rendering
    type: zip

  - path: Subterran.Basic\bin\$(configuration)\
    name: Subterran Basic
    type: zip

  - path: Examples\TropicalIsland\bin\$(configuration)\
    name: Example TropicalIsland
    type: zip