# We're using C# 6.0, so we need to adjust the platform
os: Visual Studio 2015 CTP 6

# The path also needs to be set correctly so we get the correct tools
install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

configuration: Release

# Rewrites the Verison on the DLLs
version: 1.0.{build}
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

environment:
  COVERALLS_REPO_TOKEN:
    secure: ZffVSrlIdZNrnQf+k4uej4/5pMeraSY0ctOxHMc7eUyTXGWq5wVQEH6xOI8LcbeD

nuget:
  account_feed: true
  project_feed: true

# Restore NuGet packages before running MSBuild
before_build:
  - nuget restore

build:
  verbosity: minimal
  project: Subterran.sln
  publish_nuget: true
# If the symbol server dies, disable this so nuget updates can go through
  publish_nuget_symbols: true

# This is for publishing to coveralls.io
after_test:
  - ps: >-
    .\packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -target:"packages\xunit.runners.2.0.0-rc3-build2880\tools\xunit.console.exe" "-targetargs:""Subterran.Tests\bin\$env:CONFIGURATION\Subterran.Tests.dll"" /noshadow /appveyor" -filter:"+[Subterran*]*" -output:coverage.xml
    .\packages\coveralls.io.1.2.5-beta\tools\coveralls.net.exe --opencover coverage.xml

artifacts:
  # Subterran.Toolbox contains all the Subterran libraries in the output
  - path: Subterran.Toolbox\bin\$(configuration)
    name: Subterran Libraries
    type: zip

  - path: Examples\TropicalIsland\bin\$(configuration)
    name: Tropical Island Example
    type: zip

  - path: Examples\VoxelWorld\bin\$(configuration)
    name: Voxel World Example
    type: zip
