//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subterran {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Subterran.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;{0}&quot; is ambiguous..
        /// </summary>
        internal static string GameInfo_TypeAmbiguous {
            get {
                return ResourceManager.GetString("GameInfo_TypeAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string GameInfo_TypeNotFound {
            get {
                return ResourceManager.GetString("GameInfo_TypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shader program {0} does not contain &quot;{1}&quot; uniform..
        /// </summary>
        internal static string ShaderUtils_ProgramDoesNotContainUniform {
            get {
                return ResourceManager.GetString("ShaderUtils_ProgramDoesNotContainUniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shader program {0} failed to link..
        /// </summary>
        internal static string ShaderUtils_ProgramFailedLinking {
            get {
                return ResourceManager.GetString("ShaderUtils_ProgramFailedLinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shader program {0} compiled with log:.
        /// </summary>
        internal static string ShaderUtils_ProgramWithLog {
            get {
                return ResourceManager.GetString("ShaderUtils_ProgramWithLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shader {0} failed to compile..
        /// </summary>
        internal static string ShaderUtils_ShaderFailedCompile {
            get {
                return ResourceManager.GetString("ShaderUtils_ShaderFailedCompile", resourceCulture);
            }
        }
    }
}
